version: "2"

run:
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: false

linters:
  enable:
    - govet
    - errcheck
    - errorlint
    - nilerr
    - revive
  disable:
    - varnamelen
    - tagliatelle
    - testpackage
    - paralleltest
    - thelper
    - ireturn
    - misspell
    - noctx
    - unused
    - dupl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    revive:
      severity: error
      enable-all-rules: false
      rules:
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          disabled: false
        - name: import-shadowing
          disabled: false
        - name: exported
          disabled: false
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: (_test\.go)
        text: error return value of `[^`]+` is not checked
      - linters:
          - errcheck
        path: (_test\.go)
        text: Error return value is not checked
      - linters:
          - dupl
          - gocyclo
          - funlen
          - gosec
        path: _test\.go
      - path: (.+)\.go$
        text: G404
      - path: (.+)\.go$
        text: SA1019

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/TykTechnologies)
        - blank
        - dot
