version: '3'

includes:
  tracetest: ./.taskfiles/tracetest/Taskfile.yml

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -v ./...
  test:
    desc: Run unit tests
    cmds:
      - go test -v -race -vet=off ./...

  e2e-setup:
    desc: Install e2e tests - start all e2e apps, tracetest and otel-collector
    deps:
      - tracetest
    status:
      - tracetest version
    cmds:
    - docker compose -f e2e/tracetest/docker-compose.yml -f e2e/basic/docker-compose.yml up -d --build
    - tracetest configure -g --endpoint http://localhost:11633
    - sleep 2;
    - tracetest version

  e2e-test:
    desc: Run all e2e tests scenarios with tracetest
    cmds:
     - tracetest test run -d ./e2e/basic/tests/example.yml -w -o pretty

  e2e-stop:
    desc: Stop e2e environment
    cmds:
      - docker compose -f e2e/tracetest/docker-compose.yml -f e2e/basic/docker-compose.yml down --remove-orphans

  e2e:
    desc: Install, run and clean e2e tests
    cmds:
      - task: e2e-setup
      - task: e2e-test
      - task: e2e-stop
      - task: e2e-custom-headers

  e2e-custom-headers:
    desc: Run custom-headers e2e tests (standalone, no tracetest)
    cmds:
    - cd e2e/custom-headers && docker-compose up -d --build
    - sleep 2
    - |
      echo "Testing custom mode..."
      curl -s -H "X-Correlation-ID: abc12300000000000000000000000000-abc1230000000000-01" http://localhost:8080/test | jq .
    - |
      echo "Testing upstream propagation..."
      curl -s -H "X-Correlation-ID: def45600000000000000000000000000-def4560000000000-01" http://localhost:8080/upstream | jq .
    - cd e2e/custom-headers && docker-compose down
