version: '3'

tasks:
  up:
    desc: Start the custom headers e2e test service
    cmds:
      - docker-compose up --build -d

  down:
    desc: Stop the custom headers e2e test service
    cmds:
      - docker-compose down

  logs:
    desc: Show logs from the custom headers service
    cmds:
      - docker-compose logs -f custom-headers

  test:custom:
    desc: Test custom mode (read/write custom header only)
    cmds:
      - |
        echo "Testing custom mode..."
        curl -v -H "X-Correlation-ID: abc12300000000000000000000000000-abc1230000000000-01" http://localhost:8080/test

  test:upstream:
    desc: Test upstream propagation
    cmds:
      - |
        echo "Testing upstream propagation..."
        curl -v -H "X-Correlation-ID: def45600000000000000000000000000-def4560000000000-01" http://localhost:8080/upstream

  test:hybrid:
    desc: Test hybrid mode (read custom, write standard)
    cmds:
      - docker-compose down
      - OTEL_CONTEXT_PROPAGATION=tracecontext docker-compose up --build -d
      - sleep 2
      - |
        echo "Testing hybrid mode..."
        curl -v -H "X-Correlation-ID: 0102030405060708090a0b0c0d0e0f10-1112131415161718-01" http://localhost:8080/test

  test:composite:
    desc: Test composite mode (read/write both)
    cmds:
      - docker-compose down
      - OTEL_CONTEXT_PROPAGATION=composite docker-compose up --build -d
      - sleep 2
      - |
        echo "Testing composite mode..."
        curl -v -H "X-Correlation-ID: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-bbbbbbbbbbbbbbbb-01" http://localhost:8080/test

  clean:
    desc: Clean up Docker resources
    cmds:
      - docker-compose down -v
      - docker system prune -f
