version: "3"

tasks:
  default:
    desc: "Configure tracetest"
    deps:
      - install:linux
      - install:darwin
    cmds:
      - tracetest configure -g --endpoint http://localhost:11633

  install:darwin:
    internal: true
    desc: "Install tracetest"
    status:
      - type tracetest
    platforms: [darwin]
    cmds:
      - curl -L https://raw.githubusercontent.com/kubeshop/tracetest/main/install-cli.sh | bash -s -- v0.12.2
  install:linux:
    internal: true
    desc: "Install tracetest"
    status:
      - type tracetest
    platforms: [linux]
    cmds:  # https://docs.tracetest.io/getting-started/cli-installation-reference#apt
      - curl -L https://raw.githubusercontent.com/kubeshop/tracetest/main/install-cli.sh | bash -s -- v0.12.2
