version: "3"

tasks:
  default:
    desc: "Configure tracetest"
    deps:
      - install
    cmds:
      - tracetest configure -g --endpoint http://localhost:11633

  install:
    internal: true
    desc: "Install tracetest"
    status:
      - type tracetest
    cmds:
      - curl -L https://raw.githubusercontent.com/kubeshop/tracetest/main/install-cli.sh | bash -s -- v0.12.2
